config/routes.rb
Rails.application.routes.draw do
  #Rails.application.routes.default_url_options[:"localhost:3000"]
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'users/:id', to: 'users#show', as: 'user'
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get 'mood_boards/:moodboard_id/pins', to: 'pins#index', as: 'mood_board_pins'
  post 'mood_boards/:moodboard_id/pins', to: 'pins#create'
  get 'mood_boards/:moodboard_id/pins/new', to: 'pins#new', as: 'new_mood_board_pin'
  get '/mood_boards/:moodboard_id/pins/:id', to: 'pins#show', as: 'mood_board_pin'
  patch '/mood_boards/:moodboard_id/pins/:id', to: 'pins#update'
  delete '/mood_boards/:moodboard_id/pins/:id', to:'pins#destroy'
  put '/mood_boards/:moodboard_id/pins/:id', to: 'pins#update'
  get '/mood_boards/:moodboard_id/pins/:id/edit', to: 'pins#edit', as: 'edit_mood_board_pin'

  get 'pins/:id/grab', to: 'pins#grab', as: 'grab_pin'
  post 'pins/:id/repin', to: 'pins#repin', as: 'repin_pin'
  post 'pins/:id/editing', to: 'pins#editing', as: 'editing_pin'

  #get '/mood_boards/:moodboard_id/users/:id', to: 'users#show', as: 'mood_board_user'

  ####### SEE HERE #######
  # Per Prof. Fleming: If you add any routes, the to: portion MUST NOT USE a '_' symbol 
  ####### SEE HERE #######
  root to: redirect('/mood_boards')

  # Route to the main page.
  get 'mood_boards', to: 'moodboards#index', as: 'mood_boards'
  # # Route to the create page
  post 'mood_boards', to: 'moodboards#create'
  get 'mood_boards/new', to: 'moodboards#new', as: 'new_mood_board'
  # # Route to the show page.
  get 'mood_boards/:id', to: 'moodboards#show', as: 'mood_board'
  # # Route to the edit page.
  patch 'mood_boards/:id', to: 'moodboards#update'
  put 'mood_boards/:id', to: 'moodboards#update'
  # # Route to destroy a moodboard.
  delete 'mood_boards/:id', to: 'moodboards#destroy', as: 'destroy_mood_board'
  # Route to edit page.
  get 'mood_board/:id', to: 'moodboards#edit', as: 'edit_mood_board'
  # Route to get_inspired
  get 'mood_board/:id', to: 'moodboards#getinspired', as: 'getinspired'

  get 'mood_boards/:moodboard_id/comments', to: 'comments#index', as: 'mood_board_comments'
  post 'mood_boards/:moodboard_id/comments', to: 'comments#create'
  get 'mood_boards/:moodboard_id/comments/new', to: 'comments#new', as: 'new_mood_board_comment'
  delete 'mood_boards/:moodboard_id/comments/:id', to: 'comments#destroy', as:'mood_board_comment'

  post 'mood_boards/:moodboard_id/ratings/:id', to: 'moodboards#rate', as: 'mood_board_rating'

end

app/models/pin.rb
# == Schema Information
#
# Table name: pins
#
#  id            :bigint           not null, primary key
#  hovertext     :string
#  pin_name      :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  mood_board_id :bigint
#
# Indexes
#
#  index_pins_on_mood_board_id  (mood_board_id)
#
# Foreign Keys
#
#  fk_rails_...  (mood_board_id => mood_boards.id)
#
class Pin < ApplicationRecord

    has_one_attached :image_file

    belongs_to(
        :mood_board,
        class_name: "MoodBoard",
        foreign_key: "mood_board_id",
        inverse_of: :pins
    )

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    before_action :authenticate_user!, except: [:show]

    def index
        @moodboard = MoodBoard.find(params[:moodboard_id])
        @pins = @moodboard.pins
        render :index
      end

    def show
        @moodboard = MoodBoard.find(params[:moodboard_id])
        @pin = @moodboard.pins.find(params[:id])
        if current_user
            @moodboards = current_user.mood_boards
        end
        if current_user
            @editing_mb
            @mbs = current_user.mood_boards
            @mbs.each do |f|
                if f.editing == true
                    @editing_mb = MoodBoard.find(f.id)
                end
            end
        end
        render :show
    end

    def editing
        if current_user
            @editing_mb
            @mbs = current_user.mood_boards
            @mbs.each do |f|
                if f.editing == true
                    @editing_mb = MoodBoard.find(f.id)
                end
            end
        end
        @pin = Pin.find(params[:id])
        @repin = Pin.new
        @repin.pin_name = @pin.pin_name
        @repin.hovertext = @pin.hovertext
        @repin.image_file.attach(@pin.image_file.blob)
        @repin.mood_board = @editing_mb
        @repin.save
        redirect_to mood_board_pins_url(@editing_mb)
    end

    def grab
        @moodboards = current_user.mood_boards
        @pin = Pin.find(params[:id])
        render :grab
    end

    def repin
        @pin = Pin.find(params[:id])
        @repin = Pin.new
        @repin.pin_name = @pin.pin_name
        @repin.hovertext = @pin.hovertext
        @repin.image_file.attach(@pin.image_file.blob)
        @repin.update(params.require(:pin).permit(:pin_name, :hovertext, :image_file, :mood_board_id))
        redirect_to mood_board_pins_url(@repin.mood_board)
    end

    
    def new
        @moodboard = MoodBoard.find(params[:moodboard_id])
        @pin = Pin.new
        render :new
    end

    def create
        @moodboard = MoodBoard.find(params[:moodboard_id])
        @pin = @moodboard.pins.build(params.require(:pin).permit(:pin_name, :hovertext, :image_file))
        if @pin.save
            flash[:success] = "New pin created!"
            redirect_to mood_board_pins_url(@moodboard)
        else
            flash.now[:error] = "Pin creation failed."
            render :new
        end
    end

    def edit
        @moodboard = MoodBoard.find(params[:moodboard_id])
        @pin = @moodboard.pins.find(params[:id])
        render :edit
    end

    def update
        @moodboard = MoodBoard.find(params[:moodboard_id])
        @pin = @moodboard.pins.find(params[:id])
        if @pin.update(params.require(:pin).permit(:pin_name, :hovertext, :image_file))
          flash[:success] = "Pin updated!"
          redirect_to mood_board_pin_url(@moodboard, @pin)
        else
          flash.now[:error] = "Pin update failed"
          render :edit
        end
    end

    def destroy
        @moodboard = MoodBoard.find(params[:moodboard_id])
        @pin = @moodboard.pins.find(params[:id])
        @pin.destroy
        flash[:success] = "The pin has been deleted."
        redirect_to mood_board_pins_url(@moodboard)
    end

end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/edit.html.erb
<h1>Edit Photo</h1>

<%= bootstrap_form_with model: @pin, url: mood_board_pin_path(@moodboard, @pin), method: :patch, local: true do |f| %>

    <%= f.text_field :pin_name %>
    <%= f.text_field :hovertext %>
    <%= f.file_field :image_file %>
    <%= f.submit %>

<% end %>

<p><%= link_to 'Cancel', mood_board_pins_path(@moodboard) %></p>

app/views/pins/grab.html.erb
<h1>Grab Pin!</h1>

<%= form_with model: @pin, url: repin_pin_path(@pin), method: :post, local: true do |f| %>
    <%= f.select :mood_board_id, @moodboards.collect { |m| [m.title, m.id] } %>
    <%= f.submit %>
<% end %>

app/views/pins/index.html.erb
<h1>Pin Objects</h1>

<table class="table table-striped table-hover">

  <thead class="thead-dark">
    <tr>
      <th>Pin Name</th>
      <th>Hovertext</th>
      <th>Associated Mood Board</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= link_to pin.pin_name, mood_board_pin_path(@moodboard, pin) %></td>
        <td><%= pin.hovertext %></td>
        <td><%= link_to pin.mood_board.title, mood_board_path(pin.mood_board) %>
        <% if @moodboard.user == current_user %>
          <td><%= link_to "Delete", mood_board_pin_path(@moodboard, pin), method: :delete %> | <%= link_to "Edit", edit_mood_board_pin_path(@moodboard, pin) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

<% if @moodboard.user == current_user %>
  <p class="button"><%= link_to "Create New Pin", new_mood_board_pin_path(@moodboard), class: 'btn btn-primary' %></p>
<% end %>

<p class="button"> <%= link_to "Back to the Mood Board", mood_board_path(@moodboard), class: 'btn btn-primary' %>

</table>

app/views/pins/new.html.erb
<h1>Create New Pin</h1>

<%= bootstrap_form_with model: @pin, url: mood_board_pins_path(@moodboard), method: :post, local: true do |f| %>

    <%= f.text_field :pin_name %>
    <%= f.text_field :hovertext %>
    <%= f.file_field :image_file %>
    <%= f.submit %>

<% end %>

<p><%= link_to 'Cancel', mood_board_pins_path(@moodboard) %></p>

app/views/pins/show.html.erb
<h1 class="center">Photo | <%= @pin.pin_name %></h1>

<% if @pin.mood_board.template == "Bubbles" %>
    <p class="center">
        <%= image_tag @pin.image_file,
        title: @pin.hovertext,
        class: 'bubbles',
        style: 'max-width: 32rem;  padding-top: 25px;  padding-bottom: 25px;'
        %>
    </p>
<% else %>
    <p class="center">
        <%= image_tag @pin.image_file,
        class: 'blocks',
        style: 'max-width: 32rem; padding-top: 25px; padding-bottom: 25px;'
        %>
    </p>
<% end %>

<div class="center">
    <% if @editing_mb %>
        <p class="button"><%= link_to "Add to board being editied", editing_pin_path(@pin), :method=>:post, class: 'btn btn-primary' %></p>
    <% end %>

    <% if current_user && current_user.mood_boards.exists? %>
        <p class="button"><%= link_to "Grab Image", grab_pin_path(@pin), class: 'btn btn-primary' %></p>
    <% end %>

    <% if @moodboard.user == current_user %>
        <p class="button"><%= link_to "Back to Pins index", mood_board_pins_path(@moodboard), class: 'btn btn-primary' %>
    <% end %>

    <p class="button"><%= link_to "Back to " + @pin.mood_board.title, mood_board_path(@pin.mood_board), class: 'btn btn-primary' %></p>
</div>