config/routes.rb
Rails.application.routes.draw do
  #Rails.application.routes.default_url_options[:"localhost:3000"]
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'users/:id', to: 'users#show', as: 'user'
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get 'mood_boards/:moodboard_id/pins', to: 'pins#index', as: 'mood_board_pins'
  post 'mood_boards/:moodboard_id/pins', to: 'pins#create'
  get 'mood_boards/:moodboard_id/pins/new', to: 'pins#new', as: 'new_mood_board_pin'
  get '/mood_boards/:moodboard_id/pins/:id', to: 'pins#show', as: 'mood_board_pin'
  patch '/mood_boards/:moodboard_id/pins/:id', to: 'pins#update'
  delete '/mood_boards/:moodboard_id/pins/:id', to:'pins#destroy'
  put '/mood_boards/:moodboard_id/pins/:id', to: 'pins#update'
  get '/mood_boards/:moodboard_id/pins/:id/edit', to: 'pins#edit', as: 'edit_mood_board_pin'

  get 'pins/:id/grab', to: 'pins#grab', as: 'grab_pin'
  post 'pins/:id/repin', to: 'pins#repin', as: 'repin_pin'
  post 'pins/:id/editing', to: 'pins#editing', as: 'editing_pin'

  #get '/mood_boards/:moodboard_id/users/:id', to: 'users#show', as: 'mood_board_user'

  ####### SEE HERE #######
  # Per Prof. Fleming: If you add any routes, the to: portion MUST NOT USE a '_' symbol 
  ####### SEE HERE #######
  root to: redirect('/mood_boards')

  # Route to the main page.
  get 'mood_boards', to: 'moodboards#index', as: 'mood_boards'
  # # Route to the create page
  post 'mood_boards', to: 'moodboards#create'
  get 'mood_boards/new', to: 'moodboards#new', as: 'new_mood_board'
  # # Route to the show page.
  get 'mood_boards/:id', to: 'moodboards#show', as: 'mood_board'
  # # Route to the edit page.
  patch 'mood_boards/:id', to: 'moodboards#update'
  put 'mood_boards/:id', to: 'moodboards#update'
  # # Route to destroy a moodboard.
  delete 'mood_boards/:id', to: 'moodboards#destroy', as: 'destroy_mood_board'
  # Route to edit page.
  get 'mood_board/:id', to: 'moodboards#edit', as: 'edit_mood_board'
  # Route to get_inspired
  get 'mood_board/:id', to: 'moodboards#getinspired', as: 'getinspired'

  get 'mood_boards/:moodboard_id/comments', to: 'comments#index', as: 'mood_board_comments'
  post 'mood_boards/:moodboard_id/comments', to: 'comments#create'
  get 'mood_boards/:moodboard_id/comments/new', to: 'comments#new', as: 'new_mood_board_comment'
  delete 'mood_boards/:moodboard_id/comments/:id', to: 'comments#destroy', as:'mood_board_comment'

  post 'mood_boards/:moodboard_id/ratings/:id', to: 'moodboards#rate', as: 'mood_board_rating'

end

app/models/mood_board.rb
# == Schema Information
#
# Table name: mood_boards
#
#  id            :bigint           not null, primary key
#  editing       :boolean
#  featured      :boolean
#  global_rating :integer
#  published     :boolean
#  template      :string
#  title         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :bigint
#
# Indexes
#
#  index_mood_boards_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class MoodBoard < ApplicationRecord

    has_many(
        :pins,
        class_name: "Pin",
        foreign_key: "mood_board_id",
        inverse_of: :mood_board,
        dependent: :destroy
    )

    has_many(
        :ratings,
        class_name: "Rating",
        foreign_key: "mood_board_id",
        inverse_of: :mood_board,
        dependent: :destroy
    )
    
    has_many(
        :comments,
        class_name: "Comment",
        foreign_key: "mood_board_id",
        inverse_of: :mood_board,
        dependent: :destroy
    )

    belongs_to(
        :user,
        class_name: "User",
        foreign_key: "user_id",
        inverse_of: :mood_boards
    )
    after_initialize do
        if self.new_record?
          # values will be available for new record forms.
          # ||= added  - this means if value is nil, false or undefiend, set it to default value otherwise use the existing value.
          self.featured ||= false
          self.global_rating ||= 0
          self.published ||= false
          self.template ||= "Bubbles"
        end
    end

    #validate :acceptable_image
end

app/controllers/moodboards_controller.rb
class MoodboardsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @mood_boards = MoodBoard.order(global_rating: :desc)
        render :index
    end

    def show
        @mood_board = MoodBoard.find(params[:id])
        render :show
    end

    def new
        @mood_board = MoodBoard.new
        render :new
    end

    def edit
        @mood_board = MoodBoard.find(params[:id])
        render :edit
       end 

    def create
        @mood_board = MoodBoard.new(params.require(:mood_board).permit(:title, :template))
        @mood_board.user = current_user
        if @mood_board.save
            flash[:success] = 'Moodboard was successfully created!'
            redirect_to mood_board_url(@mood_board)
        else 
            flash.now[:error] = 'Error! Unable to create moodboard.'
            render :new
        end
    end

    def update
        @mood_board = MoodBoard.find(params[:id])
        if @mood_board.update(params.require(:mood_board).permit(:title, :template, :editing, :featured))
          flash[:success] = "MoodBoard successfully updated!"
          redirect_to mood_boards_url(@mood_board)
        else
          flash.now[:error] = "MoodBoard update failed"
          render :edit
        end
      end
    # def acceptable_image
    #     return unless photo.attached?

    #     unless photo.byte_size <= 1.megabyte
    #         errors.add(:photo, "This file is too large.")
    #     end

    #     unless accetable_types = ["image/jpeg", "image/jpg", "image/png"]
    #     errors.add(:photo, "Invalid Format! Image must be JPEG, JPG, or PNG.")
    #     end
    # end
    

    def destroy
        @mood_board = MoodBoard.find(params[:id])
        @mood_board.destroy
        flash[:success] = 'Mood Board successfully destroyed.'
        redirect_to mood_boards_url
    end

    def rate
        @mood_board = MoodBoard.find(params[:id])
        Rating.create(user: current_user, mood_board: @mood_board)
        @mood_board.increment!(:global_rating)
        @mood_board.save
        redirect_to mood_board_url(@mood_board)
    end


    def getinspired
        @mood_board = MoodBoard.find(params[:id])
        @new_mood_board = MoodBoard.dup
        redirect_to mood_board_url(@new_mood_board)
    end
end

app/helpers/moodboards_helper.rb
module MoodboardsHelper
end

app/views/moodboards/_form.html.erb
<%= bootstrap_form_with model:  @mood_board, local: true do |f| %>

  <%= f.text_field :title %>
  <%= f.select :template, [["Bubbles"], ["Blocks"]], label: "Choose your Mood Board template:" %>
  <% @editing_other = false %>
  <% @mbs = current_user.mood_boards %>
  <% @mbs.each do |f| %>
    <% if f.editing == true %>
      <% if f.title != @mood_board.title %>
        <% @editing_other = true %>
      <% end %>
    <% end %>
  <% end %>
  <% if @editing_other == false %>
    <%= f.check_box :editing, label: "Editing Mode" %>
  <% end %>
  <% @featured_other = false %>
  <% @mbs2 = current_user.mood_boards %>
  <% @mbs2.each do |d| %>
    <% if d.featured == true %>
      <% if d.title != @mood_board.title %>
        <% @featured_other = true %>
      <% end %>
    <% end %>
  <% end %>
  <% if @featured_other == false %>
    <%= f.check_box :featured, label: "Feature This Board" %>
  <% end %>
  <%= f.submit %>

<% end %>

<p><td><%= link_to "Cancel", root_path %> </td>

app/views/moodboards/edit.html.erb
<h1>Edit Moodboards</h1>
<%= render "form" %>

app/views/moodboards/index.html.erb
<h1> Welcome to MoodBoards!</h1>

<table class="table table-striped table-hover">

    <thead class="thead-dark">
    <tr>
        <th>MoodBoard Title</th>
        <th>MoodBoard Template</th>
        <th>MoodBoard Rating</th>
        <th>Creator</th>
        <th>Featured?</th>
        <% if user_signed_in?%>
            <th>Modify Board</th>
        <% end %>
    </tr>
    </thead>

    <tbody>
    <% @mood_boards.each do |m| %>
    <tr>
        <td><%= link_to m.title, mood_board_path(m) %> </td>
        <td><%= m.template %></td>
        <td><%= m.global_rating %></td>
        <% if user_signed_in?%>
            <td><%= link_to m.user.username, m.user %></td>
        <% else %>
            <td><%= m.user.username %></td>
        <% end %>
        <td><%= m.featured %></td>
        <% if user_signed_in? %>
            <td>
                <% if m.user == current_user  %>
                    <%= link_to 'Edit', edit_mood_board_path(m) %> |
                    <%= link_to 'Destroy', destroy_mood_board_path(m), method: :delete %>
                <% end %>
            </td>
        <% end %>
     </tr>
    <% end %>
    </tbody>
</table>

<hr style="background-color:#000;">

<% @mood_boards.each_with_index do |m, m_index| %>
    <% if m_index < 5 %>
        <h1 style="text-align: center; font-weight: bold"><%= link_to m.title, mood_board_path(m) %></h1>
        <div class="container">
            <div class="row">
                <% m.pins.each_with_index  do |pin, p_index| %>
                    <% if p_index < 5 %>
                        <% offsets = [3,4,8,9,13,14,18,19,23,24,28,29] %>
                        <% if offsets.include?(p_index) %>
                            <div class="col-lg-6 col-md-6 col-sm-12 mb-5 mt-5">
                                <% if m.template == "Bubbles" %>
                                    <%= link_to image_tag(pin.image_file, :class=>'bubbles'), mood_board_pin_path(m, pin), title: pin.hovertext %>
                                <%else%>
                                    <%= link_to image_tag(pin.image_file, :class=>'blocks'), mood_board_pin_path(m, pin), title: pin.hovertext %>
                                <%end%>
                            </div>
                        <% else %>
                            <div class="col-lg-4 col-md-6 col-sm-12">
                                <% if m.template == "Bubbles" %>
                                    <%= link_to image_tag(pin.image_file, :class=>'bubbles'), mood_board_pin_path(m, pin), title: pin.hovertext %>
                                <%else%>
                                    <%= link_to image_tag(pin.image_file, :class=>'blocks'), mood_board_pin_path(m, pin), title: pin.hovertext %>
                                <%end%>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>
        <div class="container mb-info mr-auto">
            <h3>Rating: <%= m.global_rating %></h3>

            <% if m.user == current_user %>
                <p class="button"><%= link_to "Add/edit Pins", mood_board_pins_path(m), class: 'btn btn-primary' %></p>
                <p class="button"> <%= link_to 'Edit Mood Board', edit_mood_board_path(m), class: 'btn btn-primary' %> </p>
            <% end %>
        
        </div>
    <hr style="background-color:#000;">
    <% end %>
<% end %> 

app/views/moodboards/new.html.erb
<h1>Create a new Mood Board</h1>

<%= bootstrap_form_with model: @mood_board, method: :post, url: mood_boards_path, local: true do |f| %>


<%= f.text_field :title, placeholder: 'Enter Mood Board title here.'%>
<%= f.select :template, options_for_select(["Bubbles","Blocks"]), {}, { class: "form-control" } %>
<%= f.submit %>
<% end %>
<p><td><%= link_to "Cancel", root_path %> </td>
 

app/views/moodboards/show.html.erb
<h1 style="text-align: center"><%= @mood_board.title %></h1>
<div class="container">
    <div class="row">
        <% @mood_board.pins.each_with_index  do |pin, p_index| %>
            <% if p_index < 5 %>
                <% offsets = [3,4,8,9,13,14,18,19,23,24,28,29] %>
                <% if offsets.include?(p_index) %>
                    <div class="col-lg-6 col-md-6 col-sm-12 mb-5 mt-5">
                        <% if @mood_board.template == "Bubbles" %>
                            <%= link_to image_tag(pin.image_file, :class=>'bubbles'), mood_board_pin_path(@mood_board, pin), title: pin.hovertext %>
                        <%else%>
                            <%= link_to image_tag(pin.image_file, :class=>'blocks'), mood_board_pin_path(@mood_board, pin), title: pin.hovertext %>
                        <%end%>
                    </div>
                <% else %>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <% if @mood_board.template == "Bubbles" %>
                            <%= link_to image_tag(pin.image_file, :class=>'bubbles'), mood_board_pin_path(@mood_board, pin), title: pin.hovertext %>
                        <%else%>
                            <%= link_to image_tag(pin.image_file, :class=>'blocks'), mood_board_pin_path(@mood_board, pin), title: pin.hovertext %>
                        <%end%>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

<h2>Current Rating: <%= @mood_board.global_rating %></h2>

<p>
    <% if user_signed_in? %>
        <% if Rating.where(mood_board: @mood_board, user: current_user ).empty? %>
            <p class="button"><%= link_to "Like!", mood_board_rating_path(@mood_board), method: :post, class: 'btn btn-primary' %></p>
        <% else %>
            You have liked this board! :)
        <% end %>
    <% end %>
</p>

<% if @mood_board.user == current_user %>
    <p class="button"><%= link_to "Add/edit Pins", mood_board_pins_path(@mood_board), class: 'btn btn-primary' %>
    <p class="button"> <%= link_to 'Edit Mood Board', edit_mood_board_path(@mood_board), class: 'btn btn-primary' %> </p>
<% end %>

<p class="button"><td><%= link_to "Back to the Home Page", root_path, class: 'btn btn-primary' %> </td>

<p class="button"><%= link_to "Add a comment!", new_mood_board_comment_path(@mood_board), class: 'btn btn-primary' %></p>

<%#<p class="button"><%= link_to "Get Inspired",  getinspired_path(@mood_board), class: 'btn btn-primary'%>

<p><% @mood_board.comments.each do |m| %>
    <div class="card">
        <div class="card-body">
            <div class="card-title">
               <% if m.user %> 
                    <center> <h2><%= m.user.username %></h2> </center>
                    <% if m.user.image_file.attached? %>
                        <%= image_tag url_for(current_user.image_file),
                        class: 'w-100 rounded-circle shadow-lg d-block mx-auto',
                        style: 'max-width: 10rem;' %>
                    <% end %>
                <% else %>
                    <h2>"Anonymous"</h2>
                <% end %>
            </div>
            <div class="card-text">
                <p><%= m.message %><br>
                <% if @mood_board.user == current_user %>
                    <%= link_to "Delete", mood_board_comment_path(@mood_board, m), method: :delete %>
                <% end %>
            </div>
        </div> 
    </div>
<% end %></p>