config/routes.rb
Rails.application.routes.draw do
  #Rails.application.routes.default_url_options[:"localhost:3000"]
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'users/:id', to: 'users#show', as: 'user'
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get 'mood_boards/:moodboard_id/pins', to: 'pins#index', as: 'mood_board_pins'
  post 'mood_boards/:moodboard_id/pins', to: 'pins#create'
  get 'mood_boards/:moodboard_id/pins/new', to: 'pins#new', as: 'new_mood_board_pin'
  get '/mood_boards/:moodboard_id/pins/:id', to: 'pins#show', as: 'mood_board_pin'
  patch '/mood_boards/:moodboard_id/pins/:id', to: 'pins#update'
  delete '/mood_boards/:moodboard_id/pins/:id', to:'pins#destroy'
  put '/mood_boards/:moodboard_id/pins/:id', to: 'pins#update'
  get '/mood_boards/:moodboard_id/pins/:id/edit', to: 'pins#edit', as: 'edit_mood_board_pin'

  get 'pins/:id/grab', to: 'pins#grab', as: 'grab_pin'
  post 'pins/:id/repin', to: 'pins#repin', as: 'repin_pin'
  post 'pins/:id/editing', to: 'pins#editing', as: 'editing_pin'

  #get '/mood_boards/:moodboard_id/users/:id', to: 'users#show', as: 'mood_board_user'

  ####### SEE HERE #######
  # Per Prof. Fleming: If you add any routes, the to: portion MUST NOT USE a '_' symbol 
  ####### SEE HERE #######
  root to: redirect('/mood_boards')

  # Route to the main page.
  get 'mood_boards', to: 'moodboards#index', as: 'mood_boards'
  # # Route to the create page
  post 'mood_boards', to: 'moodboards#create'
  get 'mood_boards/new', to: 'moodboards#new', as: 'new_mood_board'
  # # Route to the show page.
  get 'mood_boards/:id', to: 'moodboards#show', as: 'mood_board'
  # # Route to the edit page.
  patch 'mood_boards/:id', to: 'moodboards#update'
  put 'mood_boards/:id', to: 'moodboards#update'
  # # Route to destroy a moodboard.
  delete 'mood_boards/:id', to: 'moodboards#destroy', as: 'destroy_mood_board'
  # Route to edit page.
  get 'mood_board/:id', to: 'moodboards#edit', as: 'edit_mood_board'
  # Route to get_inspired
  get 'mood_board/:id', to: 'moodboards#getinspired', as: 'getinspired'

  get 'mood_boards/:moodboard_id/comments', to: 'comments#index', as: 'mood_board_comments'
  post 'mood_boards/:moodboard_id/comments', to: 'comments#create'
  get 'mood_boards/:moodboard_id/comments/new', to: 'comments#new', as: 'new_mood_board_comment'
  delete 'mood_boards/:moodboard_id/comments/:id', to: 'comments#destroy', as:'mood_board_comment'

  post 'mood_boards/:moodboard_id/ratings/:id', to: 'moodboards#rate', as: 'mood_board_rating'

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
   # GET /resource/confirmation/new
   def new
    self.resource = resource_class.new
  end

  # POST /resource/confirmation
  def create
    self.resource = resource_class.send_confirmation_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_resending_confirmation_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      set_flash_message!(:notice, :confirmed)
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
    end
  end

  protected

    # The path used after resending confirmation instructions.
    def after_resending_confirmation_instructions_path_for(resource_name)
      is_navigational_format? ? new_session_path(resource_name) : '/'
    end

    # The path used after confirmation.
    def after_confirmation_path_for(resource_name, resource)
      if signed_in?(resource_name)
        signed_in_root_path(resource)
      else
        new_session_path(resource_name)
      end
    end

    def translation_scope
      'devise.confirmations'
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  prepend_before_action { request.env["devise.skip_timeout"] = true }

  def passthru
    render status: 404, plain: "Not found. Authentication passthru."
  end

  def failure
    set_flash_message! :alert, :failure, kind: OmniAuth::Utils.camelize(failed_strategy.name), reason: failure_message
    redirect_to after_omniauth_failure_path_for(resource_name)
  end

  protected

  def failed_strategy
    request.respond_to?(:get_header) ? request.get_header("omniauth.error.strategy") : request.env["omniauth.error.strategy"]
  end

  def failure_message
    exception = request.respond_to?(:get_header) ? request.get_header("omniauth.error") : request.env["omniauth.error"]
    error   = exception.error_reason if exception.respond_to?(:error_reason)
    error ||= exception.error        if exception.respond_to?(:error)
    error ||= (request.respond_to?(:get_header) ? request.get_header("omniauth.error.type") : request.env["omniauth.error.type"]).to_s
    error.to_s.humanize if error
  end

  def after_omniauth_failure_path_for(scope)
    new_session_path(scope)
  end

  def translation_scope
    'devise.omniauth_callbacks'
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  prepend_before_action :require_no_authentication
  # Render the #edit only if coming from a reset password email link
  append_before_action :assert_reset_token_passed, only: :edit

  # GET /resource/password/new
  def new
    self.resource = resource_class.new
  end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    self.resource = resource_class.new
    set_minimum_password_length
    resource.reset_password_token = params[:reset_password_token]
  end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      if Devise.sign_in_after_reset_password
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message!(:notice, flash_message)
        resource.after_database_authentication
        sign_in(resource_name, resource)
      else
        set_flash_message!(:notice, :updated_not_active)
      end
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      set_minimum_password_length
      respond_with resource
    end
  end

  protected
    def after_resetting_password_path_for(resource)
      Devise.sign_in_after_reset_password ? after_sign_in_path_for(resource) : new_session_path(resource_name)
    end

    # The path used after sending reset password instructions
    def after_sending_reset_password_instructions_path_for(resource_name)
      new_session_path(resource_name) if is_navigational_format?
    end

    # Check if a reset_password_token is provided in the request
    def assert_reset_token_passed
      if params[:reset_password_token].blank?
        set_flash_message(:alert, :no_token)
        redirect_to new_session_path(resource_name)
      end
    end

    # Check if proper Lockable module methods are present & unlock strategy
    # allows to unlock resource on password reset
    def unlockable?(resource)
      resource.respond_to?(:unlock_access!) &&
        resource.respond_to?(:unlock_strategy_enabled?) &&
        resource.unlock_strategy_enabled?(:email)
    end

    def translation_scope
      'devise.passwords'
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy]
  prepend_before_action :set_minimum_password_length, only: [:new, :edit]


  def new
    build_resource
    yield resource if block_given?
    respond_with resource
  end

  # GET /resource/sign_up
  def new
    build_resource
    yield resource if block_given?
    respond_with resource
  end
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    render :edit
  end
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message! :notice, :destroyed
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    expire_data_after_sign_in!
    redirect_to new_registration_path(resource_name)
  end

  protected

  def update_needs_confirmation?(resource, previous)
    resource.respond_to?(:pending_reconfirmation?) &&
      resource.pending_reconfirmation? &&
      previous != resource.unconfirmed_email
  end

  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash = {})
    self.resource = resource_class.new_with_session(hash, session)
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource) if is_navigational_format?
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    scope = Devise::Mapping.find_scope!(resource)
    router_name = Devise.mappings[scope].router_name
    context = router_name ? send(router_name) : self
    context.respond_to?(:root_path) ? context.root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    sign_in_after_change_password? ? signed_in_root_path(resource) : new_session_path(resource_name)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", force: true)
    self.resource = send(:"current_#{resource_name}")
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up, keys: [:username])

  end

  def account_update_params
    devise_parameter_sanitizer.sanitize(:sign_up, keys: [:username])
  end

  def translation_scope
    'devise.registrations'
  end

  private

  def set_flash_message_for_update(resource, prev_unconfirmed_email)
    return unless is_flashing_format?

    flash_key = if update_needs_confirmation?(resource, prev_unconfirmed_email)
                  :update_needs_confirmation
                elsif sign_in_after_change_password?
                  :updated
                else
                  :updated_but_not_signed_in
                end
    set_flash_message :notice, flash_key
  end

  def sign_in_after_change_password?
    return true if account_update_params[:password].blank?

    Devise.sign_in_after_change_password
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  prepend_before_action :require_no_authentication, only: [:new, :create]
  prepend_before_action :allow_params_authentication!, only: :create
  prepend_before_action :verify_signed_out_user, only: :destroy
  prepend_before_action(only: [:create, :destroy]) { request.env["devise.skip_timeout"] = true }

   
  # GET /resource/sign_in
  def new
   self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
   respond_with(resource, serialize_options(resource))
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  protected

  def sign_in_params
    devise_parameter_sanitizer.sanitize(:sign_in)
  end

  def serialize_options(resource)
    methods = resource_class.authentication_keys.dup
    methods = methods.keys if methods.is_a?(Hash)
    methods << :password if resource.respond_to?(:password)
    { methods: methods, only: [:password] }
  end

  def auth_options
    { scope: resource_name, recall: "#{controller_path}#new" }
  end

  def translation_scope
    'devise.sessions'
  end

  private

  # Check if there is no signed in user before doing the sign out.
  #
  # If there is no signed in user, it will set the flash message and redirect
  # to the after_sign_out path.
  def verify_signed_out_user
    if all_signed_out?
      set_flash_message! :notice, :already_signed_out

      respond_to_on_destroy
    end
  end

  def all_signed_out?
    users = Devise.mappings.keys.map { |s| warden.user(scope: s, run_callbacks: false) }

    users.all?(&:blank?)
  end

  def respond_to_on_destroy
    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name) }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<center><h1><%= current_user.username %></h1></center>

<% if current_user.image_file.attached? %> 
  <%= image_tag url_for(current_user.image_file),
                    class: 'w-100 rounded-circle shadow-lg d-block mx-auto',
                      style: 'max-width: 10rem;' %>
<% end %>



<<%= bootstrap_form_with model: current_user, url: user_path(current_user), method: :patch, local: true do |f|%>
    <%= f.file_field :image_file %>
    <%= f.text_field :about_me %>
    <%= f.text_field :email %>
    <%= f.submit %>
<% end %>


<p><%= link_to 'Cancel', user_path(current_user) %></p>

app/views/users/index.html.erb
<h2> User index</h2>

<% @users.each do |user| %>
<tr>
<%=  user.username %>
<%= user.email %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>


<%= form_with model: @user, url: sign_up_path  do |f|%>
<div class="mb-3">
  <%= f.label :username%>
  <%= f.text_field :username, class: "form-control", placeholder: "Bobby2000" %>
  </div>
  <div class="mb-3">
  <%= f.label :password%>
  <%= f.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
  <%= f.label :password_confirmation%>
  <%= f.password_field :password, class: "form-control", placeholder: "password" %>
    </div>

    <div class="mb-3">
  <%= f.submit %>
  </div>
<%end%>

app/views/users/show.html.erb
<center> <h1><%= @user.username %></h1></center>


<% if @user.image_file.attached? %>
	<%= image_tag url_for(current_user.image_file),
	class: 'w-100 rounded-circle shadow-lg d-block mx-auto',
	style: 'max-width: 10rem;' %>
<% end %>  


<p>About Me: <%= @user.about_me%></p>






<p class="button">
<%= link_to 'Edit Profile', edit_user_path(current_user), class: 'btn btn-primary' %>
<%= link_to "Back to the Moodboard index", root_path, class: 'btn btn-primary' %> 
<%= link_to 'Create Mood Board', new_mood_board_path, class: 'btn btn-primary' %>
</p>


<%# Featured Moodboard %>
<hr style="background-color:#000;">
<h1 style="text-align: center; font-weight: bold;">Featured MoodBoard</h1>
<hr style="background-color:#000;">

<% @mbs = @user.mood_boards %>
<% @mbs.each do |m| %>
<% if m.featured %>
    <h1 style="text-align: center; font-weight: bold"><%=link_to m.title, mood_board_path(m)%></h1>
    <div class="container"> 
        <div class="row">
            <%if m.featured? %>
                <% m.pins.each_with_index do |pin, p_index|%>
                    <%if p_index < 5 %>
                        <% offsets = [3,4,8,9,13,14,18,19,23,24,28,29] %>
                        <%if offsets.include?(p_index) %>
                            <div class="col-lg-6 col-md-6 col-sm-12 mb-5 mt-5">
                                <% if m.template == "Bubbles" %>
                                    <%= link_to image_tag(pin.image_file, :class=>'bubbles'), mood_board_pin_path(m, pin)%>
                                <%else%>
                                    <%= link_to image_tag(pin.image_file, :class=>'blocks'), mood_board_pin_path(m, pin)%>
                                <%end%>
                            </div>
                        <%else%>
                            <div class="col-lg-4 col-md-6 col-sm-12">
                                <% if m.template == "Bubbles" %>
                                    <%= link_to image_tag(pin.image_file, :class=>'bubbles'), mood_board_pin_path(m, pin)%>
                                <%else%>
                                    <%= link_to image_tag(pin.image_file, :class=>'blocks'), mood_board_pin_path(m, pin)%>
                                <%end%>
                            </div>
                        <%end%>
                    <%end%>
                <%end%>
                <div class="container mb-info mr-auto">
                    <h3>Rating: <%= m.global_rating %></h3>
                </div>        
            <%end%>
        </div>
    </div>
    <% end %> 
<%end%>
<%# <p>TODO: Link to  Feature Mood Board. <%= link_to 'Feature', Feature_moodboard_path(@moodboard) </p> %>




<table class="table table-striped table-hover">
  <thead class="table-primary">
    <tr>
      <th>Mood Boards</th>
      <th>Template</th>
      <th>Rating</th>
      <th>Featured</th>
      <th>Modify Board</th>
    </tr>
  </thead>
  <tbody>
    <% @mood_board.each do |m| %>
      <tr>
        <td><%= link_to m.title, mood_board_path(m) %> </td>
        <td><%= m.template %></td>
        <td><%= m.global_rating %></td>
        <td><%= m.featured %></td>
        <td>
        <%= link_to 'Edit', edit_mood_board_path(m) %> |
        <%= link_to 'Destroy', destroy_mood_board_path(m), method: :delete %>
        </td>  
      </tr>
    <% end %>
  </tbody>
</table>

                    